Send git error messages instead of empty strings
Previously, we sent an empty string when we couldn't determine certain
git attributes.

Now, we send a git error message and we don't send the empty strings.

Which will allow us to show richer help text iff a CLI run is invoked
that tries to use `event.git.sha` but we can't determine a sha. For
example:

 ```
 ❯  RWX_HOST=cloud.local ~/code/cli/rwx run patch-test.yml
 Error: Failed to initiate run:

 Error: Could not evaluate initialization parameter `ref`
 Could not determine `event.git.sha`: You are not in a git repository
 Fix the error and rerun the CLI or set `--init`.
 ```